-- ========================================================================================
-- TEMPLATE DE BASE DE DADOS: NÓS - WEBSITES CASAMENTOS 
-- Executar este script no SQL Editor do Supabase para inicializar um novo cliente
-- ========================================================================================

-- 1. CRIAR TABELA DE MENSAGENS (Mural de Recados)
CREATE TABLE public.mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    mensagem TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CRIAR TABELA DE CONVIDADOS (Sistema de RSVP)
CREATE TABLE public.convidados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    confirmado BOOLEAN DEFAULT false,
    data_confirmacao TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CONFIGURAÇÕES DE SEGURANÇA (Row Level Security)
-- Como o site é público e os convidados não fazem login com password, 
-- permitimos a leitura e inserção pública através da chave anónima (anon key).

-- Ativar RLS
ALTER TABLE public.mensagens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.convidados ENABLE ROW LEVEL SECURITY;

-- Políticas para a Tabela MENSAGENS
CREATE POLICY "Permitir leitura pública de mensagens" ON public.mensagens FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública de mensagens" ON public.mensagens FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir eliminação pública" ON public.mensagens FOR DELETE USING (true); -- Necessário para a função de Admin apagar

-- Políticas para a Tabela CONVIDADOS
CREATE POLICY "Permitir leitura pública de convidados" ON public.convidados FOR SELECT USING (true);
CREATE POLICY "Permitir atualização pública do RSVP" ON public.convidados FOR UPDATE USING (true);

-- ========================================================================================
-- FIM DO SCRIPT
-- ========================================================================================
